"use client";

import { useState } from "react";
import { showToast } from "@/lib/toast";
import { InterviewPrepResult, QuestionType, Difficulty } from "@/types/interview";

// ─── Constants ────────────────────────────────────────────────────────────────

const QUESTION_TYPE_OPTIONS: { value: QuestionType; label: string; icon: string; desc: string }[] = [
  { value: "hr",        label: "HR / Behavioural", icon: "🤝", desc: "Culture fit, communication, conflict resolution" },
  { value: "technical", label: "Technical",         icon: "💻", desc: "DSA, system design, language-specific concepts" },
  { value: "mixed",     label: "Mixed",             icon: "🎯", desc: "Balanced mix of HR and Technical questions" },
];

const DIFFICULTY_CONFIG: Record<Difficulty, { label: string; classes: string; dot: string }> = {
  Easy:   { label: "Easy",   classes: "bg-green-50 text-green-700 border-green-200",  dot: "bg-green-500" },
  Medium: { label: "Medium", classes: "bg-yellow-50 text-yellow-700 border-yellow-200", dot: "bg-yellow-500" },
  Hard:   { label: "Hard",   classes: "bg-red-50 text-red-700 border-red-200",        dot: "bg-red-500" },
};

const TYPE_CONFIG: Record<"HR" | "Technical", { classes: string }> = {
  HR:        { classes: "bg-blue-50 text-blue-700" },
  Technical: { classes: "bg-purple-50 text-purple-700" },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function DifficultyBadge({ difficulty }: { difficulty: Difficulty }) {
  const cfg = DIFFICULTY_CONFIG[difficulty];
  return (
    <span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-medium ${cfg.classes}`}>
      <span className={`h-1.5 w-1.5 rounded-full ${cfg.dot}`} />
      {cfg.label}
    </span>
  );
}

function TypeBadge({ type }: { type: "HR" | "Technical" }) {
  const cfg = TYPE_CONFIG[type];
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${cfg.classes}`}>
      {type}
    </span>
  );
}

// ─── PDF Download ─────────────────────────────────────────────────────────────

async function downloadAsPdf(result: InterviewPrepResult) {
  // Dynamic import — jsPDF is large, only load when needed
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ── Header ──────────────────────────────────────────────────────────────────
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Interview Preparation Questions", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`${result.role} at ${result.company}`, margin, y);
  y += 5;
  doc.text(
    `Type: ${result.questionType.toUpperCase()} · ${result.count} questions · Generated ${new Date(result.generatedAt).toLocaleDateString()}`,
    margin,
    y
  );
  y += 8;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // ── Questions ────────────────────────────────────────────────────────────────
  doc.setTextColor(0);

  for (const q of result.questions) {
    // Check if we need a new page
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    // Question number + badges
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`Q${q.id}. [${q.type}] [${q.difficulty}]`, margin, y);
    y += 6;

    // Question text — wrap long lines
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const questionLines = doc.splitTextToSize(q.question, contentW);
    doc.text(questionLines, margin, y);
    y += questionLines.length * 5 + 2;

    // Hint
    doc.setFontSize(9);
    doc.setTextColor(100);
    const hintLines = doc.splitTextToSize(`💡 Hint: ${q.hint}`, contentW - 4);
    doc.text(hintLines, margin + 2, y);
    y += hintLines.length * 4.5 + 6;

    doc.setTextColor(0);
  }

  // ── Footer ───────────────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ApplyAI · Page ${i} of ${pageCount}`,
      pageW / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: "center" }
    );
  }

  doc.save(`interview-prep-${result.role.replace(/\s+/g, "-").toLowerCase()}.pdf`);
}

// ─── Form state ───────────────────────────────────────────────────────────────

interface FormState {
  role: string;
  company: string;
  questionType: QuestionType;
  count: number;
  jobDescription: string;
}

interface FormErrors {
  role?: string;
  company?: string;
  count?: string;
}

function validateForm(form: FormState): FormErrors {
  const errors: FormErrors = {};
  if (!form.role.trim()) errors.role = "Role is required.";
  else if (form.role.trim().length < 2) errors.role = "Role must be at least 2 characters.";
  if (!form.company.trim()) errors.company = "Company is required.";
  else if (form.company.trim().length < 2) errors.company = "Company must be at least 2 characters.";
  if (form.count < 1 || form.count > 20) errors.count = "Count must be between 1 and 20.";
  return errors;
}

// ─── Page ─────────────────────────────────────────────────────────────────────

const INITIAL_FORM: FormState = {
  role: "",
  company: "",
  questionType: "mixed",
  count: 10,
  jobDescription: "",
};

const inputClass =
  "w-full rounded-lg border border-zinc-300 px-3 py-2.5 text-sm text-zinc-900 placeholder:text-zinc-400 focus:outline-none focus:ring-2 focus:ring-zinc-900 focus:border-transparent transition";
const inputErrorClass =
  "w-full rounded-lg border border-red-400 px-3 py-2.5 text-sm text-zinc-900 placeholder:text-zinc-400 focus:outline-none focus:ring-2 focus:ring-red-400 focus:border-transparent transition";

export default function InterviewPrepPage() {
  const [form, setForm] = useState<FormState>(INITIAL_FORM);
  const [errors, setErrors] = useState<FormErrors>({});
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<InterviewPrepResult | null>(null);
  const [downloading, setDownloading] = useState(false);
  const [expandedId, setExpandedId] = useState<number | null>(null);

  // Button is only active when both required fields are filled
  const canSubmit = form.role.trim().length >= 2 && form.company.trim().length >= 2;

  function handleChange(
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>
  ) {
    const { name, value } = e.target;
    setForm((prev) => ({
      ...prev,
      [name]: name === "count" ? Number(value) : value,
    }));
    if (errors[name as keyof FormErrors]) {
      setErrors((prev) => ({ ...prev, [name]: undefined }));
    }
  }

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();

    const validationErrors = validateForm(form);
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      showToast.error("Please fix the errors before generating.");
      return;
    }

    setLoading(true);
    setResult(null);

    try {
      const res = await fetch("/api/interview-prep", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          role: form.role.trim(),
          company: form.company.trim(),
          questionType: form.questionType,
          count: form.count,
          jobDescription: form.jobDescription.trim() || undefined,
        }),
      });

      const data = await res.json();

      if (!res.ok || !data.success) {
        showToast.error(data.message ?? "Failed to generate questions.");
        return;
      }

      setResult(data.data as InterviewPrepResult);
      showToast.success(`${data.data.count} questions generated!`);
    } catch {
      showToast.error("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  async function handleDownload() {
    if (!result) return;
    setDownloading(true);
    try {
      await downloadAsPdf(result);
      showToast.success("PDF downloaded!");
    } catch {
      showToast.error("Failed to generate PDF. Please try again.");
    } finally {
      setDownloading(false);
    }
  }

  return (
    <div className="p-6 md:p-8 space-y-6 max-w-4xl">
      {/* Page header */}
      <div>
        <h1 className="text-2xl font-semibold text-zinc-900">Interview Prep</h1>
        <p className="text-sm text-zinc-500 mt-0.5">
          Generate AI-powered interview questions tailored to your role and company.
        </p>
      </div>

      {/* ── Generator form ────────────────────────────────────────────────── */}
      <form onSubmit={handleGenerate} noValidate className="rounded-xl border border-zinc-200 bg-white p-6 shadow-sm space-y-5">
        <h2 className="text-sm font-semibold text-zinc-900">Configure Questions</h2>

        {/* Role + Company */}
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <div className="flex flex-col gap-1.5">
            <label className="text-sm font-medium text-zinc-700">
              Role <span className="text-red-500">*</span>
            </label>
            <input
              name="role"
              type="text"
              placeholder="e.g. Frontend Developer"
              value={form.role}
              onChange={handleChange}
              className={errors.role ? inputErrorClass : inputClass}
            />
            {errors.role && <p className="text-xs text-red-500">{errors.role}</p>}
          </div>

          <div className="flex flex-col gap-1.5">
            <label className="text-sm font-medium text-zinc-700">
              Company <span className="text-red-500">*</span>
            </label>
            <input
              name="company"
              type="text"
              placeholder="e.g. Google"
              value={form.company}
              onChange={handleChange}
              className={errors.company ? inputErrorClass : inputClass}
            />
            {errors.company && <p className="text-xs text-red-500">{errors.company}</p>}
          </div>
        </div>

        {/* Question type selector */}
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-zinc-700">Question Type</label>
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-3">
            {QUESTION_TYPE_OPTIONS.map((opt) => (
              <button
                key={opt.value}
                type="button"
                onClick={() => setForm((prev) => ({ ...prev, questionType: opt.value }))}
                className={`flex flex-col gap-1 rounded-xl border px-4 py-3 text-left transition-all ${
                  form.questionType === opt.value
                    ? "border-zinc-900 bg-zinc-900 text-white"
                    : "border-zinc-200 hover:border-zinc-400 text-zinc-700"
                }`}
              >
                <span className="text-lg">{opt.icon}</span>
                <span className="text-sm font-medium">{opt.label}</span>
                <span className={`text-xs ${form.questionType === opt.value ? "text-zinc-300" : "text-zinc-400"}`}>
                  {opt.desc}
                </span>
              </button>
            ))}
          </div>
        </div>

        {/* Count slider */}
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-zinc-700">
            Number of Questions:{" "}
            <span className="font-bold text-zinc-900">{form.count}</span>
            <span className="text-zinc-400 font-normal"> (max 20)</span>
          </label>
          <input
            name="count"
            type="range"
            min={1}
            max={20}
            value={form.count}
            onChange={handleChange}
            className="w-full accent-zinc-900"
          />
          <div className="flex justify-between text-xs text-zinc-400">
            <span>1</span>
            <span>5</span>
            <span>10</span>
            <span>15</span>
            <span>20</span>
          </div>
          {errors.count && <p className="text-xs text-red-500">{errors.count}</p>}
        </div>

        {/* Optional JD */}
        <div className="flex flex-col gap-1.5">
          <label className="text-sm font-medium text-zinc-700">
            Job Description{" "}
            <span className="text-xs font-normal text-zinc-400">(optional — improves question relevance)</span>
          </label>
          <textarea
            name="jobDescription"
            rows={4}
            placeholder="Paste the job description here for more targeted questions..."
            value={form.jobDescription}
            onChange={handleChange}
            className={`${inputClass} resize-none`}
          />
        </div>

        {/* Submit */}
        <button
          type="submit"
          disabled={!canSubmit || loading}
          className="w-full rounded-lg bg-zinc-900 py-3 text-sm font-medium text-white hover:bg-zinc-700 disabled:opacity-50 disabled:cursor-not-allowed transition"
        >
          {loading ? "⏳ Generating questions..." : "🎯 Generate Interview Questions"}
        </button>
      </form>

      {/* ── Results ───────────────────────────────────────────────────────── */}
      {result && (
        <div className="space-y-4">
          {/* Results header */}
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <h2 className="text-base font-semibold text-zinc-900">
                {result.count} Questions — {result.role} at {result.company}
              </h2>
              <p className="text-xs text-zinc-500 mt-0.5">
                {result.questionType.toUpperCase()} · Generated {new Date(result.generatedAt).toLocaleString()}
              </p>
            </div>
            <button
              onClick={handleDownload}
              disabled={downloading}
              className="flex items-center gap-2 rounded-lg border border-zinc-300 px-4 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-50 disabled:cursor-not-allowed transition"
            >
              {downloading ? "⏳ Generating PDF..." : "⬇️ Download PDF"}
            </button>
          </div>

          {/* Difficulty summary */}
          <div className="flex flex-wrap gap-2">
            {(["Easy", "Medium", "Hard"] as const).map((d) => {
              const count = result.questions.filter((q) => q.difficulty === d).length;
              if (count === 0) return null;
              const cfg = DIFFICULTY_CONFIG[d];
              return (
                <span key={d} className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-medium ${cfg.classes}`}>
                  <span className={`h-1.5 w-1.5 rounded-full ${cfg.dot}`} />
                  {count} {d}
                </span>
              );
            })}
          </div>

          {/* Question cards */}
          <div className="space-y-3">
            {result.questions.map((q) => (
              <div
                key={q.id}
                className="rounded-xl border border-zinc-200 bg-white shadow-sm overflow-hidden"
              >
                {/* Question header — always visible */}
                <button
                  onClick={() => setExpandedId(expandedId === q.id ? null : q.id)}
                  className="w-full flex items-start gap-4 px-5 py-4 text-left hover:bg-zinc-50 transition-colors"
                >
                  {/* Number */}
                  <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-zinc-100 text-xs font-bold text-zinc-700">
                    {q.id}
                  </span>

                  {/* Question text + badges */}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-zinc-900 leading-snug">
                      {q.question}
                    </p>
                    <div className="flex items-center gap-2 mt-2">
                      <TypeBadge type={q.type} />
                      <DifficultyBadge difficulty={q.difficulty} />
                    </div>
                  </div>

                  {/* Expand chevron */}
                  <svg
                    className={`h-4 w-4 shrink-0 text-zinc-400 transition-transform mt-1 ${expandedId === q.id ? "rotate-180" : ""}`}
                    fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </button>

                {/* Hint — shown when expanded */}
                {expandedId === q.id && (
                  <div className="px-5 pb-4 border-t border-zinc-100">
                    <div className="mt-3 rounded-lg bg-blue-50 border border-blue-200 px-4 py-3">
                      <p className="text-xs font-semibold text-blue-600 mb-1">💡 Preparation Hint</p>
                      <p className="text-sm text-blue-800 leading-relaxed">{q.hint}</p>
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Bottom download button */}
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="w-full rounded-lg border border-zinc-300 py-3 text-sm font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-50 disabled:cursor-not-allowed transition"
          >
            {downloading ? "⏳ Generating PDF..." : "⬇️ Download All Questions as PDF"}
          </button>
        </div>
      )}
    </div>
  );
}
